# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Marco Ziccardi
tagline:          ''
description:      'Marco Ziccardi - Half computer scientist, half software engineer, half sport and mountain addict.'
url:              https://mziccard.me
baseurl:          /

author:
  name:           'Marco Ziccardi'
  url:            https://twitter.com/mziccard

paginate:         5

# Custom vars
logo:             mziccard.jpg
twitter:          mziccard
disqus_shortname: mziccard
github:
  repo:           https://github.com/mziccard.github.io
  user:           mziccard
keywords:         'programming, computer science, software engineering, mathematics, algorithms'
